language: ruby

services:
  - docker

git:
  depth: false

env:
  global:
    - secure: "V6Fww6hQLaoajQmJnS8cyUAv7AEEwtrJDXkZC08/CRs10PoozP0idzgYCk3aHM0l2BiN/dvZCb9rNL9ZLv9LYmnZCvQ/OVOC6vFZHWebcd0wf3RWAPZzRsAXrFtRxDu9JbzJcQsW95c+9rKrtiiFSIQHUni1CYEbmFx4J7hB3Fl5Hb60wMbP5aanS9LP2X0f5Rl7idkXXxxY/3eFg4ZZWIODlCnuiYNuyuU26iR5I9VsL6+bu77aFZJ85z1ywvVvqV3ZIY0rr2EWQPtg4gilAnnkFjPDGz6vYIATuMPHflK/M+gcvLJqt0B/s8wMPX2mtNWJ191um2JoYBgZh6dykg89YUIsR4DFcLGTLRyK5X/6iLiBbkl7UwKU4/UDdiKt6mnh9KG8kM5c6U9QXUglvfoA7x4KlLNRPohqbxZskw5OTnf30zMKiDSL0buCA8Y1m5PBAdqR53/ruyxDZLgGd2Qv0lTktBxYYD04PBUbrW7SSxbTkzOudvXrXbGc0B2YhJnMTl3qkUSiXcxKyrROKdhMKL+Wg96YRnkJ01eMfqK9w56iAMfe3TIl+jFnvLLUFZlKC6jClW1tb9eRs+gxW6OLuDl44ReZ6q9qJhOXAIXXsJ3uon7ZT86hyQ8C8t4rteUUEXfCT/+lPtqmlD3WmkZ3abpHhlBIY9/GfqoNoyM="
    - PARALLEL_TEST_PROCESSORS=3
  matrix:
    - TEST_GROUP=1
    - TEST_GROUP=2
    - TEST_GROUP=3

install: skip

stages:
  - test
  - stable package debian 9
  - stable package debian 10
  - nightly package debian 9
  - nightly package debian 10

# by default stage=test
# matrix only works for top level script
script:
  - >
    docker-compose run
    -e "PARALLEL_TEST_PROCESSORS=$PARALLEL_TEST_PROCESSORS"
    -e "TEST_GROUP=$TEST_GROUP"
    app make rspec

jobs:
  include:
    - stage: test
      name: Rubocop and Bundle Audit
      script:
        - docker-compose run app make lint

    - stage: test
      name: PGQ Processors rspec
      script:
        - docker-compose run app make test-pgq-processors

    - stage: stable package debian 9
      if: branch != master OR tag =~ ^.*$
      name: Stable Debian stretch package
      script: &build_stretch
        - >
          docker-compose run --name yeti-web-build-stretch app-stretch make package &&
          docker commit yeti-web-build-stretch yeti-web:built-stretch
      deploy:
        skip_cleanup: true
        provider: script
        script: docker run --name yeti-web-deploy-stretch yeti-web:built-stretch ci/deploy.sh "$API_ENDPOINT" stretch "${TRAVIS_TAG:0:3}" main /build/*.deb
        on:
          tags: true
          condition: "$TRAVIS_TAG != *-master*"
          repo: yeti-switch/yeti-web

    - stage: stable package debian 10
      if: branch != master OR tag =~ ^.*$
      name: Stable Debian buster package
      script: &build_buster
        - >
          docker-compose run --name yeti-web-build-buster app-buster make package &&
          docker commit yeti-web-build-buster yeti-web:built-buster
      deploy:
        skip_cleanup: true
        provider: script
        script: docker run --name yeti-web-deploy-buster yeti-web:built-buster ci/deploy.sh "$API_ENDPOINT" buster "${TRAVIS_TAG:0:3}" main /build/*.deb
        on:
          tags: true
          condition: "$TRAVIS_TAG != *-master*"
          repo: yeti-switch/yeti-web


    - stage: nightly package debian 9
      if: branch = master
      name: Nightly Debian stretch package
      script: *build_stretch
      deploy:
        skip_cleanup: true
        provider: script
        script: docker run --name yeti-web-deploy-stretch yeti-web:built-stretch ci/deploy.sh "$API_ENDPOINT" stretch nightly main /build/*.deb
        on:
          all_branches: true
          repo: yeti-switch/yeti-web


    - stage: nightly package debian 10
      if: branch = master
      name: Nightly Debian buster package
      script: *build_stretch
      deploy:
        skip_cleanup: true
        provider: script
        script: docker run --name yeti-web-deploy-buster yeti-web:built-buster ci/deploy.sh "$API_ENDPOINT" buster nightly main /build/*.deb
        on:
          all_branches: true
          repo: yeti-switch/yeti-web
