queue: "cdr_billing"
consumers: ["cdr_billing"]
syslog_program_name: "YETI-cdr-billing"
pid_file: "/run/yeti-cdr-billing/yeti-cdr-billing.pid"
mail_to: "bug-report@yeti-switch.org"
mail_from: "yeti-cdr-billing@example.com"
mail_subject: "Exception happened in CDR billing"
