development: &default
  adapter: postgresql
  encoding: unicode
  database: yeti_dev
  pool: 5
  username: postgres
  password:
  host: 127.0.0.1
  schema_search_path: >
    gui, public, switch,
    billing, class4, runtime_stats,
    sys, logs, data_import
  port: 5432
  #min_messages: warning

test:
  <<: *default
  database: yeti_test<%= ENV['TEST_ENV_NUMBER'] %>

secondbase:
  development: &default_cdr
    adapter: postgresql
    encoding: unicode
    database: yeti_cdr_dev
    pool: 5
    username: postgres
    password:
    host: 127.0.0.1
    schema_search_path: 'cdr, reports, billing, public'
    port: 5432
    #min_messages: warning

  test:
    <<: *default_cdr
    database: yeti_cdr_test<%= ENV['TEST_ENV_NUMBER'] %>
